# This docker compose is intended to setup a developer 
#
version: "3.3"
services:
  # This container runs our Azure function code. 
  prime_dev:
    build:
      context: .
      dockerfile: Dockerfile_dev
    volumes: # Attach the PWD into the image
      - type: bind
        source: ./target
        target: /prime-data-hub-router
    entrypoint: [/prime-data-hub-router/start_func.sh]
    environment:
      # this storage account key is not a secret. It just looks like one.
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
      - POSTGRES_USER=prime
      - POSTGRES_PASSWORD=changeIT!
      - POSTGRES_URL=jdbc:postgresql://host.docker.internal:5432/prime_data_hub
      - PRIME_ENVIRONMENT=local
      - AZ_PHD__ELR__USER=foo
      - AZ_PHD__ELR__PASS=pass
      - AZ_PHD__ELR_TEST__USER=foo
      - AZ_PHD__ELR_TEST__PASS=pass
      - AZ_PHD__ELR_PROD__USER=foo
      - AZ_PHD__ELR_PROD__PASS=pass
      - TX_PHD__ELR_TEST__USER=foo
      - TX_PHD__ELR_TEST__PASS=pass
      - TX_PHD__ELR_DEBUG__USER=foo
      - TX_PHD__ELR_DEBUG__PASS=pass
    depends_on: [azurite]
    ports:
      - 7071:7071 # default function port
      - 5005:5005 # Java debug port

  # Azurite is the Azure storage emulator for local development
  azurite: 
    image: mcr.microsoft.com/azure-storage/azurite
    ports:  
      - 10000:10000 
      - 10001:10001

  #local SFTP server as a receive point
  sftp:
    image: atmoz/sftp
    ports:
        - "2222:22"
    volumes:
      - ./target/sftp:/home/foo/upload        
    command: foo:pass:::upload     
     
