swagger: '2.0'
info:
  description: The PRIME Data Hub API
  version: 0.1.0
  title: Prime Data Hub API
  # put the contact info for your development or API team
  contact:
    email: usds@cdc.gov

paths:
  /reports:
    post:
      summary: Post a report to the data hub
      description: Post a CSV to the data for validation and processing
      parameters:
        - in: header
          name: client
          description: The client's name (eg. simple_report)
          type: string
          required: true
        - in: header
          name: x-functions-key
          description: The Azure function for the end-point
          type: string
          required: true
      consumes:
        - text/csv
      produces:
        - application/json
      responses:
        201:
          description: Success
        401:
          description: Invalid request
        500:
          description: Internal Server Error