name: Prime Data Hub Test CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

defaults:
  run:
    working-directory: prime-router

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
        with:
          postgresql version: 12.5
          postgresql db: prime_data_hub
          postgresql user: ${{ secrets.POSTGRESQL_TEST_USER }}
          postgresql password: ${{ secrets.POSTGRESQL_TEST_PWD }}
       
      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
           java-version: 11
      
      - name: Build Maven Package
        run: mvn -B clean package --file pom.xml

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag primedatahubtestprimedevregistry.azurecr.io/prime-data-hub-test:${{ github.sha }}
      
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.ACR_TEST_USER }}
          password: ${{ secrets.ACR_TEST_PWD }}
          login-server: primedatahubtestprimedevregistry.azurecr.io
          
      - name : Push Docker Image
        run: docker push primedatahubtestprimedevregistry.azurecr.io/prime-data-hub-test:${{ github.sha }}
