name: Prime Data Hub Test CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

defaults:
  run:
    working-directory: prime-router

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
      with:
        postgresql version: 12.5
        postgresql db: prime_data_hub
        postgresql user: ${{ secrets.POSTGRESQL_TEST_USER }}
        postgresql password: ${{ secrets.POSTGRESQL_TEST_PWD }}

    - name: Github Action for wget
      uses: wei/wget@ca0a6b7f0fdd7ffbe9d4cec0b9696f2dc658d3c9
      with:
        args: wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.3.0/flyway-commandline-7.3.0-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-7.3.0/flyway /usr/local/bin

    # - name: Build Package with Maven
    #   uses: comchangs/action-maven@54db702e085ac767dad94c87e84499afb9d77162
    #   run: mvn clean package

    # - name: Build the Docker image
    #   uses: actions/checkout@v2
    #   run: docker build . --file Dockerfile --tag prime-data-hub:$(date +%s)
      
#     - uses: Azure/docker-login@v1
#     - name: Azure Container Registry Login
#       with:
#         # Container registry username
#         username: # default is 
#         # Container registry password
#         password: # default is 
#         # Container registry server url
#         login-server: # default is https://index.docker.io/v1/
