name: Prime Data Hub

on:
  push:
    branches: [ test, production ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        run: |
               if [ "$GITHUB_BASE_REF" == "production" ]
               then
                   echo "Building for the production environment."
                   export RESOURCE_GROUP=prime-data-hub
                   export ACR_REPO=primedatahubregistry
               else
                   echo "Building for the test environment."
                   export RESOURCE_GROUP=prime-data-hub-test
                   export ACR_REPO=primedatahubtestprimedevregistry.azurecr.io
               fi
               env

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

      - name: Update Azure Functions App
        run: az functionapp update --resource-group prime-data-hub-test --name prime-data-hub-test

      - name: Set Azure Function Default Key
        run: |
              az functionapp function keys set \
              --resource-group prime-data-hub-test \
              --name prime-data-hub-test \
              --function-name reports \
              --key-name default \
              --key-value ${{ secrets.AZ_FXNS_TEST_DEFAULT_KEY }}

      - name: Set PostgreSQL Environment Variables
        run: | 
              az functionapp config appsettings set \
              --resource-group prime-data-hub-test \
              --name prime-data-hub-test \
              --settings POSTGRES_USER=${{ secrets.POSTGRESQL_TEST_USER }}@prime-data-hub-test POSTGRES_PASSWORD=${{ secrets.POSTGRESQL_TEST_PWD }} \
                         POSTGRES_URL=jdbc:postgresql://prime-data-hub-test.postgres.database.azure.com:5432/prime_data_hub?sslmode=require

      - name: Set SFTP Environment Variables
        run: |
              az functionapp config appsettings set \
              --resource-group prime-data-hub-test \
              --name prime-data-hub-test \
              --settings PRIME_ENVIRONMENT=test ${{ secrets.SFTP_TEST_AZ_CREDS }}
