name: Prime Data Hub

on:
  push:
    branches: [ test, production ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        run: |
               if [ "$GITHUB_BASE_REF" == "production" ]
               then
                   echo "Deploying to the production environment."
                   echo >> $GITHUB_ENV RESOURCE_GROUP=prime-data-hub-prod
               else
                   echo "Deploying to the test environment."
                   echo >> $GITHUB_ENV RESOURCE_GROUP=prime-data-hub-test
               fi
               env

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

      - name: Update Azure Functions App
        run: az functionapp update --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.RESOURCE_GROUP }}

      - name: Set Azure Function Default Key
        run: |
              az functionapp function keys set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.RESOURCE_GROUP }} \
              --function-name reports \
              --key-name default \
              --key-value ${{ secrets.AZ_FXNS_TEST_DEFAULT_KEY }}

      - name: Set PostgreSQL Environment Variables
        run: | 
              az functionapp config appsettings set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.RESOURCE_GROUP }} \
              --settings POSTGRES_USER=${{ secrets.POSTGRESQL_TEST_USER }}@${{ env.RESOURCE_GROUP }} \
                         POSTGRES_PASSWORD=${{ secrets.POSTGRESQL_TEST_PWD }} \
                         POSTGRES_URL=jdbc:postgresql://${{ env.RESOURCE_GROUP }}.postgres.database.azure.com:5432/prime_data_hub?sslmode=require

      - name: Set SFTP Environment Variables
        run: |
              az functionapp config appsettings set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.RESOURCE_GROUP }} \
              --settings PRIME_ENVIRONMENT=test ${{ secrets.SFTP_TEST_AZ_CREDS }}
